language: php

php:
  - 7.0

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - mysql -e 'create database `dev_heycommunity`;'
  - composer self-update
  - composer install -n
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate:refresh --seed -n

script:
  - ./vendor/bin/php-cs-fixer fix app
  - ./vendor/bin/php-cs-fixer fix database
  - ./vendor/bin/phpcs --config-set default_standard PSR2
  - ./vendor/bin/phpcs app
  - ./vendor/bin/phpcs database
